name: Metrics

on:
  schedule: # Update every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: kwenziwa
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Johannesburg
          output_action: none
          filename: metrics.svg

      - name: Push Metrics to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
